# This script allows you to try various combinations of Modulus
# features by changing only this config.yaml file. For best
# performance, we recommend the below defaults for each architecture.
# You can modify them by editing the  correponding entries in this 
# file
# WARNING: Setting "exact_continuity" to true or setting the arch
# as "ModifiedFourierNetArch" increases the memory requirements of the 
# problem. Batchsizes may need to be reduced for such cases.

# Arch	                        Start Lr	Max Steps	Decay Steps
# FullyConnectedArch	        1.00E-03	1500000	        15000	   
# FourierNetArch                1.00E-03	400000	        7500	   
# ModifiedFourierNetArch 	1.00E-03	400000	        7500	   
# SirenArch                     2.00E-05	500000	        5000	   
# DGMArch                       1.00E-03        1500000         15000           

defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr
  - optimizer: adam
  - loss: sum
  - _self_

run_mode: 'train'

custom:
  arch: "FourierNetArch"
  parameterized: false
  turbulent: true
  num_samples: 3
  exact_continuity: False
  quasirandom: false
  adaptive_activations: false
  includeData: true
  dataOnly: false
  initialization_data_dir : ""

graph:
  func_arch: true

save_filetypes : "vtk" #,npz"
network_dir : "./data"
initialization_network_dir : ""


scheduler: 
  decay_rate: 0.95
  decay_steps: 1000       # Change this based on arch chosen

optimizer: 
  lr: 1e-3              # Change this based on arch chosen

training:
  rec_validation_freq: 1000
  rec_inference_freq: 2000
  rec_monitor_freq: 1000
  rec_constraint_freq: 2000
  max_steps: 100000            # Change this based on arch chosen


batch_size:
  channelGlobalModifier: 1
  batchPerEpoch: 100
  inlet: 512
  outlet: 512
  channelNoSlip: 1024
  solidNoSlip: 1536
  channelInteriorLR: 4096
  channelInteriorHR: 4096
  symmetry: 1024
  integral_continuity: 2048
  num_integral_continuity: 8
